apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: divesh212/order-service2:tag1
        env:
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              key: JAEGER_HOST
              name: config-map
        ports:
        - containerPort: 8092
